default_stages: [commit]

repos:
  # check yaml and end of file fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  # nbqa autopep8 and ruff
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    - id: nbqa-autopep8
      additional_dependencies: [autopep8==2.0.2]
    - id: nbqa-ruff
      additional_dependencies: [ruff==0.0.254]

  # autofix using autopep8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8

  # checkstyle using ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
      - id: ruff
