name: publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        matpower-version: ["7.0", "7.1"]
        platform: [octave]

    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Install Octave (Linux)
        if: matrix.platform == 'octave'
        uses: MATPOWER/action-install-octave-linux@v1

      - name: Download matpower ${{ matrix.python-version }}
        run: |
          curl -L https://github.com/MATPOWER/matpower/archive/refs/tags/${{ matrix.matpower-version }}.zip > matpower.zip
          unzip matpower.zip -d temps
          mv temps/matpower-${{ matrix.matpower-version }} matpower
          cp matpowerpip/__init__.py matpower/__init__.py

      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt

      - name: Install package
        run: |
          pip install -e .

      - name: Test package
        run: |
          pytest -n auto -rA -c pyproject.toml --cov-report term-missing --cov=matpower --nbmake

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Download matpower ${{ matrix.python-version }}
        run: |
          curl -L https://github.com/MATPOWER/matpower/archive/refs/tags/${{ matrix.matpower-version }}.zip > matpower.zip
          unzip matpower.zip -d temps
          mv temps/matpower-${{ matrix.matpower-version }} matpower
          cp matpowerpip/__init__.py matpower/__init__.py

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
